copyright: Copyright &copy;2022-2022, Loyd Hook.

edit_uri: ""

extra:
  generator: false

markdown_extensions:
  - attr_list

nav:
  - Home: index.md
  - Release Documents:
      - Release Notes: release_notes.md
      - Release History: release_history.md
  - Best Practises:
      - General: best_practises_software_development.md
      - C++: best_practises_cpp.md
# - Code of Conduct: code_of_conduct.md
# - Contributing Guide: contributing.md
  - License: license.md

plugins:
  - search

repo_url: https://github.com/FAA-VAIL-Project/openGCAS

site_name: openGCAS - GroundCollision Avoidance System
# site_url: **TODO**
site_description: GroundCollision Avoidance System
site_author: FAA-VAIL-Project Team

theme:
  favicon: img/Icon.png
  features:
    - search.highlight
    - search.suggest
  language: en
  logo: img/Logo.png
  name: material
  palette:
    primary: blue
    accent: red

